name: parser
channels:
  - chen
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports.csv=1.0.7
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cheroot=8.5.2
  - cherrypy=18.6.0
  - cryptography=3.3.1
  - cuda92=1.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - feedparser=6.0.2
  - freetype=2.10.4
  - future=0.18.2
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - importlib_resources=5.1.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jaraco.classes=3.2.1
  - jaraco.collections=3.2.0
  - jaraco.functools=3.2.1
  - jaraco.text=3.5.0
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libsvm=323
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.6.2
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.0
  - more-itertools=8.7.0
  - mysql-connector-c=6.1.11
  - mysqlclient=2.0.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - nltk=3.4.4
  - notebook=6.2.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pattern=3.6.0
  - pdfminer.six=20201018
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.1
  - pip=21.0.1
  - portend=2.7.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pyenchant=1.6.9
  - pygments=2.8.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-docx=0.8.10
  - python_abi=3.6
  - pytorch=0.4.1
  - pytz=2020.1
  - pyzmq=20.0.0
  - readline=8.1
  - repoze.lru=0.7
  - requests=2.25.1
  - routes=2.5.1
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sgmllib3k=1.0.0
  - simplejson=3.17.2
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.33.0
  - tempora=4.0.1
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=4.3.3
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zc.lockfile=2.0
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - typing-extensions==3.7.4.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
