optimizer:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.001
    betas: [0.9,0.999]
    weight_decay: 0

evaluation:
  metrics:
  - per_question_accuracy

training:
  experiment_name: STAR_baseline_2dcnn_mlp
  batch_size: 128
  max_epochs: 50
  checkpoint_interval: 150
  evaluation_interval: 150
  log_interval: 10
  early_stop:
    criteria: actionqa/per_question_accuracy
    minimize: false
#mmf_run config=projects/STAR/2dcnn_mlp/defaults.yaml datasets=actionqa model=2dcnn_mlp run_type=train_val