optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

evaluation:
  metrics:
  - per_question_accuracy

training:
  experiment_name: bert
  max_epochs: 20
  batch_size: 32
  checkpoint_interval: 500
  evaluation_interval: 500
  log_interval: 5
  early_stop:
    criteria: actionqa/per_question_accuracy
    minimize: false 
#CUDA_VISIBLE_DEVICES=1 mmf_run config=projects/actionqa/BERT/defaults.yaml datasets=actionqa model=bert run_type=train_val 
#CUDA_VISIBLE_DEVICES=1 mmf_predict config=projects/actionqa/BERT/defaults.yaml checkpoint.resume_file=../../../checkpoints/sr_bert_4g/models/model_10000.ckpt datasets=actionqa model=bert run_type=test env.report_dir=../../../baselines/

#srun --gres=gpu:1 -N 1 --mem=1T --time 2:00:00 -I mmf_predict config=projects/actionqa/BERT/defaults.yaml checkpoint.resume_file=../../../checkpoints/sr_bert_4g/models/model_10000.ckpt datasets=actionqa model=bert run_type=test env.report_dir=../../../baselines/