optimizer:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 0.0002

evaluation:
  metrics:
  - accuracy
training:
  experiment_name: lstm
  max_epochs: 10
  batch_size: 16
  checkpoint_interval: 1000
  evaluation_interval: 2000
  log_interval: 10
  early_stop:
    criteria: actionqa/accuracy
    minimize: false
#CUDA_VISIBLE_DEVICES=0 mmf_run config=projects/actionqa/lstm/defaults.yaml datasets=actionqa model=language_only_model run_type=train env.save_dir=./save/lstm/
#CUDA_VISIBLE_DEVICES=2 mmf_predict config=projects/actionqa/lstm/defaults.yaml checkpoint.resume_file=./save/lstm/models/model_20000.ckpt datasets=actionqa model=language_only_model run_type=test evaluation.predict=True evaluation.evaluate=False env.report_dir=../../../baselines/