dataset_config:
  epickitchens:
    data_dir: ${env.data_dir}
    include_whole_img: true
    max_img_seq_len: 12
    max_txt_seq_len: 12
    img_root: ${env.data_dir}/datasets/epickitchens/image/rgb
    annotation:
      actions: ${env.data_dir}/datasets/epickitchens/processed_EPIC_train_action_labels.pth
      objects: ${env.data_dir}/datasets/epickitchens/EPIC_train_object_labels.csv
      video_info: ${env.data_dir}/datasets/epickitchens/EPIC_video_info.csv
      splits: ${env.data_dir}/datasets/epickitchens/splits.pth
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 12
          p_txt_mask_up: 1
          p_txt_mask_down: 3

