optimizer:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 0.0002

evaluation:
  metrics:
  - accuracy
  
training:
  experiment_name: cnn_lstm
  max_epochs: 10
  batch_size: 16
  checkpoint_interval: 1000
  evaluation_interval: 2000000000
  log_interval: 10
  early_stop:
    criteria: actionqa/accuracy
    minimize: false
#CUDA_VISIBLE_DEVICES=5 mmf_run config=projects/actionqa/cnn_lstm/defaults.yaml datasets=actionqa model=cnn_lstm_for_vqa run_type=train env.save_dir=./save/cnn_lstm/
#CUDA_VISIBLE_DEVICES=2 mmf_predict config=projects/actionqa/cnn_lstm/defaults.yaml checkpoint.resume_file=./save/cnn_lstm/models/model_24000.ckpt datasets=actionqa model=cnn_lstm_for_vqa run_type=test evaluation.predict=True evaluation.evaluate=False env.report_dir=../../../baselines/